# Generated by Django 5.2.1 on 2025-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=300)),
                ('collegeName', models.CharField(max_length=200)),
            ],
        ),
    ]
